"""
Script to store the country codes for the countries in the world to be used in 
the Bing News Search API script.
"""

country_codes = {
    'argentina': 'es-AR',
    'australia': 'en-AU',
    'austria': 'de-AT',
    'belgium': 'nl-BE',
    'brazil': 'pt-BR',
    'canada': 'en-CA',
    'chile': 'es-CL',
    'colombia': 'es-CO',
    'costa rica': 'es-CR',
    'czech republic': 'cs-CZ',
    'denmark': 'da-DK',
    'dominican republic': 'es-DO',
    'ecuador': 'es-EC',
    'egypt': 'ar-EG',
    'finland': 'fi-FI',
    'france': 'fr-FR',
    'germany': 'de-DE',
    'greece': 'el-GR',
    'guatemala': 'es-GT',
    'honduras': 'es-HN',
    'hong kong': 'zh-HK',
    'hungary': 'hu-HU',
    'india': 'en-IN',
    'indonesia': 'id-ID',
    'ireland': 'en-IE',
    'israel': 'he-IL',
    'italy': 'it-IT',
    'japan': 'ja-JP',
    'kenya': 'en-KE',
    'malaysia': 'ms-MY',
    'mexico': 'es-MX',
    'netherlands': 'nl-NL',
    'new zealand': 'en-NZ',
    'nicaragua': 'es-NI',
    'nigeria': 'en-NG',
    'norway': 'no-NO',
    'panama': 'es-PA',
    'paraguay': 'es-PY',
    'peru': 'es-PE',
    'philippines': 'en-PH',
    'poland': 'pl-PL',
    'portugal': 'pt-PT',
    'puerto rico': 'es-PR',
    'romania': 'ro-RO',
    'russia': 'ru-RU',
    'saudi arabia': 'ar-SA',
    'singapore': 'en-SG',
    'south africa': 'en-ZA',
    'south korea': 'ko-KR',
    'spain': 'es-ES',
    'sweden': 'sv-SE',
    'switzerland': 'de-CH',
    'taiwan': 'zh-TW',
    'thailand': 'th-TH',
    'turkey': 'tr-TR',
    'ukraine': 'uk-UA',
    'united kingdom': 'en-GB',
    'united states': 'en-US',
    'uruguay': 'es-UY',
    'venezuela': 'es-VE',
    'vietnam': 'vi-VN'
}
